import {api} from './api.js';import {$,bind,modal,closeModal,toast,pet,coinIcon,diamondIcon,fmt} from './ui.js';import {sound,toggle,muted} from './audio.js';
let timer;export function stopTimer(){clearInterval(timer)}
export async function play(root,level,onExit,existing){
 stopTimer();let a=existing||await api('/attempts',{level});let busy=false;let syncAt=performance.now(),elapsed=a.server_now-a.started;
 root.innerHTML=`<div class="row between game-header"><div><div class="eyebrow">${a.tier} / LEVEL ${a.level}</div><h2>Find your way out.</h2></div><button class="btn secondary small" id="exit">Exit level</button></div><div class="game-layout"><div class="board-wrap"><div id="board" class="board" style="--size:${a.board.size};grid-template-columns:repeat(${a.board.size},1fr);grid-template-rows:repeat(${a.board.size},1fr)"></div></div><aside class="game-side"><div class="card"><div class="statlabel">Your time</div><div id="timer" class="timer">00:00</div><div class="progress"><i id="timebar" style="width:0"></i></div><small class="muted">Finish in 45s for 3 diamonds</small></div><div class="card"><div class="statlabel">Lives remaining</div><p id="hearts" class="hearts"></p><small class="muted" id="remaining"></small></div><div class="card"><h3>Look before you tap</h3><p class="muted" style="font-size:13px">Tap an arrow to send it straight out of the grid. A blocked path costs one life.</p><button class="btn secondary small" id="sound">${muted?'Sound off':'Sound on'}</button></div><div class="mini-pets">${pet()}${pet()}</div></aside></div>`;
 $('#sound').onclick=()=>{$('#sound').textContent=toggle()?'Sound off':'Sound on'};
 $('#exit').onclick=()=>modal(`<h2>Leave this level?</h2><p class="muted">This attempt will end. You can restart with five free lives.</p><button class="btn danger" id="confirmexit">Exit level</button><button class="btn secondary" id="stay">Keep playing</button>`);
 $('#modal').addEventListener('click',async function exitHandler(e){if(e.target.id==='stay')closeModal();if(e.target.id==='confirmexit'){try{await api('/attempts/'+a.id+'/exit',{});closeModal();stopTimer();onExit()}catch(err){toast(err.message)}}},{signal:controller().signal});
 function render(){if(!$('#board'))return;$('#board').innerHTML=a.board.arrows.map(x=>`<button class="arrow" data-id="${x.id}" aria-label="Arrow ${x.dx===1?'right':x.dx===-1?'left':x.dy===1?'down':'up'}, row ${x.y+1}, column ${x.x+1}" style="grid-column:${x.x+1};grid-row:${x.y+1};--dx:${x.dx};--dy:${x.dy}"><svg viewBox="0 0 60 60" aria-hidden="true" style="rotate:${x.dx===1?0:x.dy===1?90:x.dx===-1?180:270}deg"><path d="M12 30H46M33 17L46 30 33 43" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>`).join('');$('#hearts').textContent='♥'.repeat(a.lives)+'♡'.repeat(Math.max(0,5-a.lives));$('#remaining').textContent=a.board.arrows.length+' arrows left · '+a.collisions+' collisions';bind('.arrow',move)}
 async function move(el){if(busy||a.status!=='playing')return;busy=true;el.classList.add('selected');const request_id=crypto.randomUUID();const send=()=>api('/attempts/'+a.id+'/move',{arrow_id:Number(el.dataset.id),request_id});try{let next;try{next=await send()}catch(e){if(e instanceof TypeError)next=await send();else throw e}a=next;elapsed=a.server_now-a.started;syncAt=performance.now();el.classList.remove('selected');el.classList.add(a.collision?'collision':'fly');sound(a.collision?'collision':'move');await new Promise(r=>setTimeout(r,330));render();if(a.status==='exhausted')exhausted();if(a.status==='complete')complete()}catch(e){toast(e.message);el.classList.remove('selected')}finally{busy=false}}
 function exhausted(){const price=[10,25,35][a.purchases];modal(`<div class="eyebrow">TAKE ANOTHER LOOK</div><h2>Out of lives.</h2><p class="muted">Restart with five free lives${price?', or use earned coins for one extra life.':'. You have used all three extra lives.'}</p>${price?`<button class="btn" id="buy">Get 1 life · ${price} coins</button>`:''}<button class="btn secondary" id="restart">Restart level</button><button class="link" id="end">Exit</button>`);if(price)$('#buy').onclick=async()=>{try{a=await api('/attempts/'+a.id+'/life',{});closeModal();render()}catch(e){toast(e.message)}};$('#restart').onclick=()=>{closeModal();play(root,a.level,onExit).catch(e=>toast(e.message))};$('#end').onclick=async()=>{await api('/attempts/'+a.id+'/exit',{});closeModal();stopTimer();onExit()}}
 function complete(){stopTimer();$('#timer').textContent=fmt(a.seconds);modal(`<div class="eyebrow">GRID CLEARED</div><h2>${a.stars>=1.5?'Beautiful escape.':'Keep practicing.'}</h2><div class="stars" style="font-size:27px">${'★'.repeat(Math.round(a.stars))}${'☆'.repeat(5-Math.round(a.stars))}</div><p>${a.stars.toFixed(1)} / 5 stars · ${a.seconds.toFixed(1)} seconds</p><p class="muted">${a.stars>=1.5?'The next level is unlocked.':'Reach 1.5 stars to unlock the next level.'}</p><p><span class="coin">● ${a.payout.coins} coins</span> &nbsp; <span class="diamond">◆ ${a.payout.diamonds} diamonds</span></p><button class="btn" id="collect">Collect rewards</button><button class="btn secondary" id="nothanks">No thanks</button>`);for(const collect of [true,false])$(collect?'#collect':'#nothanks').onclick=async()=>{try{await api('/attempts/'+a.id+'/reward',{collect});if(collect)sound('coin');closeModal();onExit()}catch(e){toast(e.message)}}}
 render();timer=setInterval(()=>{if($('#timer')){$('#timer').textContent=fmt(elapsed+(performance.now()-syncAt)/1000);$('#timebar').style.width=Math.min(100,(elapsed+(performance.now()-syncAt)/1000)/45*100)+'%'}},150);if(a.status==='exhausted')exhausted();
}
let ctrl;function controller(){ctrl?.abort();ctrl=new AbortController();return ctrl}
